# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network :private_network, ip: "192.168.56.8"
  config.vm.hostname = "minimal-go-server.test"
  config.ssh.insert_key = false
  config.vm.provision "shell", path: "golang-install.sh"
  config.vm.provision "file", source: "../web-server.go", destination: "web-server.go"

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
  end
end
